baseURL = 'https://abrhoda.github.io'
languageCode = 'en-us'
title = 'Alexander Rhoda'
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]
# Home meta description
description = "Exploring software concepts with building (but mostly breaking) software."

# Intro on main page, content in markdown
homeIntroTitle = 'Howdy and Welcome!'
homeIntroContent = """
I'm a software engineer who is armed with a $10 Amazon Basics keyboard, vim, a refurbished HP ProDesk running fedora linux, and a deep loathing for having to install a dependency to take care of anything. So enjoy!

If that's interesting to you, feel free to read more seriously [about me](/about) or to look at my [posts](/posts).
"""

# Appearance
theme = 'auto'
colorPalette = 'gruvebox'
hideHeader = false
showFooter = false
footerContent = 'Random footer content to see how it displays'
faviconPath = 'favicons'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "~ (home)"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'gruvbox'

[[params.social]]
name = "github"
url = "https://github.com/abrhoda"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"
